# Generated by Django 5.0.4 on 2024-04-24 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='reciever_contactnumber',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +977-XXXXXXXXXX (where X is a digit).', regex='^\\+977-\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reciever_telephone1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reciever_telephone2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_contactnumber',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +977-XXXXXXXXXX (where X is a digit).', regex='^\\+977-\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_telephone1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_telephone2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
